# Generated by Django 5.2.5 on 2025-10-16 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_customuser_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10),
        ),
    ]
