# Generated by Django 5.2.5 on 2025-10-22 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ('exam', '0005_questionbank_difficulty'),
   ]

    operations = [
    ]
